# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1de93d098c4e05af311bfcfc429b1d33db43407fccc1efffdecba4a56acc4870845a1d635c72b57ddd6fcf9ec14c7f6f9347f3474954297721811292ee19d74c

test:
  secret_key_base: 0611bb77821143d96350438f8f0f7f9e2bbb6b022270c25bc741933daac4bb329a603e64d206c3c9aeb31ba7688e76ee5cbde840c57c07f5aa742c58a8f7ae1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
